default: &default
 adapter: postgresql
 username: iphefnfxalfxbg
 password: 2075b0ba49ff3fbc3780839d20ca65b64bb2001fd4da916bad5cc85223fa94f3
 host: ec2-46-137-113-157.eu-west-1.compute.amazonaws.com
 port: 5432
  
development:
 <<: *default
 database: d5tr89b7amr8ct

production:
 <<: *default
 database: d5tr89b7amr8ct
